version: '3.8'

services:
  # Redis sidecar for caching
  species-redis:
    image: redis:6.2-alpine
    container_name: species-redis
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"

  # Node.js species service
  species-service:
    build:
      context: ./src/server
      dockerfile: Dockerfile
    image: sca-en-prototype/species-service:latest
    container_name: species-service
    depends_on:
      - species-redis
    ports:
      - "3000:3000"
    environment:
      - REDIS_URL=redis://species-redis:6379
      - DB_PATH=/app/data/species.db
      - REQUEST_LIMIT=100
      - CACHE_TTL=30
    volumes:
      - db-data:/app/data

volumes:
  redis-data:
  db-data:
